---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
SiteConfig:
  extensions:
    - vendor/md/uiowa-bar/code/UiowaBarSiteConfigExtension
SilverStripe\Assets\Flysystem\AssetAdapter:
  file_permissions:
    'file':
      'public': '0644'
      'private': '0600'